spring:
  application:
    name: ec-gateway
server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
feign:
  httpclient:
    enabled: true
zuul:
  #ignored-services: microservice-provider-user                        # 需要忽视的服务(配置后将不会被路由)
  routes:
    user:                                                            # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /user/**                                                 # 想要映射到的路径
      service-id: ec-consumer-user     # Eureka中的serviceId
    auth:
      path: /auth/**
      service-id: ec-consumer-auth
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000